version: "3.8"
services:
  easypost-tools-ui:
    build: .
    restart: always
    networks:
      - advoc8-easypost-tool
    labels:
      - traefik.enable=true
    depends_on:
      - easypost-tools-db
    volumes:
      - ./src:/var/www/html/
  easypost-tools-db:
    image: 'mariadb:10.8.2'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - advoc8-easypost-tool

volumes:
  database-data:
    driver: local

networks:
  advoc8-easypost-tool:
    name: advoc8-easypost-tool
