version: "3.8"
services:
  easypost-tools-ui:
    build: .
    restart: always
    networks:
      - easypost-tools-ui
      - traefik
    labels:
      - traefik.enable=true
    depends_on:
      - easypost-tools-db
    volumes:
      - ./src:/var/www/html/
  easypost-tools-db:
    image: 'mariadb:10.8.2'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - easypost-tools-ui

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  easypost-tools-ui:
    name: easypost-tools-ui
